baseURL = 'https://steadyspace.net/'
languageCode = 'en-us'
title = 'steady space'
theme = 'PaperMod'

[params]
  env = "production"

[params.assets]
  customCSS = ["css/extra.css"]

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
